[build]
  base = "."
  command = """
    cd karirin &&
    npm install &&
    npm install @rollup/rollup-linux-x64-gnu &&
    npm run build
  """
  publish = "karirin/dist"

[build.environment]
  NODE_VERSION = "18"
  VITE_BASE_URL = "/"
  # Allow these environment variables to be exposed in client-side code
  SECRETS_SCAN_OMIT_KEYS = "VITE_SUPABASE_URL,VITE_SUPABASE_ANON_KEY"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 