[build]
  base = "karirin"
  command = """
    rm -rf node_modules package-lock.json &&
    npm install &&
    npm install @rollup/rollup-linux-x64-gnu &&
    npm run build
  """
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  VITE_BASE_URL = "/"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 